<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>promise es5</title>
    <style></style>
  </head>
  <body>
    <script>
      // 自定义Promise函数模块: IIFE
      (function (window) {
        const PENDING = "pending";
        const RESOLVED = "fulfilled";
        const REJECTED = "rejected";
        // Promise构造函数
        // executor: 执行器函数（同步执行）
        function Promise(executor) {
          const self = this;
          self.status = PENDING;
          self.data = undefined;
          self.callbacks = [];

          function resolve(value) {
            if (self.status !== PENDING) {
              return;
            }
            // 将状态改为resolved
            self.status = RESOLVED;
            // 保存value数据
            self.data = value;
            // 如果有待执行的callback函数，立即异步执行回调函数onResolved
            if (self.callbacks.length > 0) {
              setTimeout(() => {
                self.callbacks.forEach((callbacksObj) => {
                  callbacksObj.onResolved(value);
                });
              });
            }
          }

          function reject(reason) {
            if (self.status !== PENDING) {
              return;
            }
            // 将状态改为resolved
            self.status = REJECTED;
            // 保存value数据
            self.data = reason;
            // 如果有待执行的callback函数，立即异步执行回调函数onRejected
            if (self.callbacks.length > 0) {
              setTimeout(() => {
                self.callbacks.forEach((callbacksObj) => {
                  callbacksObj.onRejected(reason);
                });
              });
            }
          }

          // 立即同步执行executor
          try {
            executor(resolve, reject);
          } catch (error) {
            reject(error);
          }
        }

        // Promise原型对象的then(),指定成功和失败的回调函数，返回一个新的Promise对象
        Promise.prototype.then = function (onResolved, onRejected) {
          onResolved =
            typeof onResolved === "function" ? onResolved : (value) => value;
          onRejected =
            typeof onRejected === "function"
              ? onRejected
              : (reason) => {
                  throw reason;
                };

          const self = this;
          return new Promise((resolve, reject) => {
            function handle(callback) {
              try {
                const result = callback(self.data);
                if (result instanceof Promise) {
                  result.then(
                    (value) => resolve(value),
                    (reason) => reject(reason)
                  );
                  // 简洁版
                  // result.then(resolve, reject)
                } else {
                  resolve(result);
                }
              } catch (error) {
                reject(error);
              }
            }

            if (self.status === PENDING) {
              self.callbacks.push({
                onResolved(value) {
                  handle(onResolved);
                },
                onRejected(reason) {
                  handle(onRejected);
                },
              });
            } else if (self.status === RESOLVED) {
              setTimeout(() => {
                handle(onResolved);
              });
            } else {
              // self.status = REJECTED
              setTimeout(() => {
                handle(onRejected);
              });
            }
          });
        };

        // Promise原型对象的catch()，指定失败的回调函数，返回一个新的promise对象
        Promise.prototype.catch = function (onRejected) {
          return this.then(undefined, onRejected);
        };

        // Promise函数对象的 resolve 方法
        //返回一个新的Promise对象,Promise.resolve()中可以传入Promise
        Promise.resolve = function (value) {
          return new Promise((resolve, reject) => {
            if (value instanceof Promise) {
              value.then(resolve, reject);
            } else {
              resolve(value);
            }
          });
        };

        // Promise函数对象的 reject 方法
        //返回一个新的Promise对象 Promise.reject中不能再传入Promise
        Promise.reject = function (reason) {
          return new Promise((resolve, reject) => {
            reject(reason);
          });
        };

        // Promise函数对象的all方法
        Promise.all = function (promises) {
          const values = new Array(promises.length);
          let successCount = 0;
          return new Promise((resolve, reject) => {
            promises.forEach((p, index) => {
              Promise.resolve(p).then(
                (value) => {
                  successCount++;
                  values[index] = value;
                  if (successCount === promises.length) {
                    resolve(values);
                  }
                },
                // 如果失败
                (reason) => {
                  reject(reason);
                }
              );
            });
          });
        };

        // Promise函数对象的race方法
        Promise.race = function (promises) {
          return new Promise((resolve, reject) => {
            promises.forEach((p) => {
              Promise.resolve(p).then(
                (value) => {
                  resolve(value);
                },
                (reason) => {
                  reject(reason);
                }
              );
            });
          });
        };

        // 向外暴露promise函数
        window.Promise = Promise;
      })(window);
    </script>
  </body>
</html>
